### PR TITLE
Add support for multi-domain apps in VN

### PR DESCRIPTION
**Pull request by jjackson26**
See TestVoiceNavigator.html for an example of how to use the new config param

### CODE REVIEW

**Comment by jjackson26** [comment]
@swarajban @jagill Quick PR when you have a minute

**Comment by jagill** [comment]
Looks nice.  Should we put a similar comment in the Starter App?

**Comment by swarajban** [comment]
ya looks nice, I'll add something similar to the starter app when updating JS SDK w/ GM changes

**Comment by swarajban** [comment]
Added this functionality in the other PR, closing this one

**Pull request closed without merging**
